config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'games#index'

  get '/' => "games#index"

  get '/games/:id/comments' => 'comments#new', as: :new_comment
  # post '/games/:id/comments' => 'comments#create', as: :create_comment

  resources :games do
    resources :comments
  end

  # Commented out to fix merge conflict
  # _____________________________________
  # get '/games/:id' => "games#show", as: "game"
  # post '/games' => "games#create"



  delete '/sessions' => "sessions#delete"

  resources :ownerships

  # get '/users/:id/edit' => 'users#edit'
  # patch '/users/:id' => 'users#edit'

  resources :users do
    resources :friendships
  end
  resources :sessions

  post '/games/:id/votes' => 'votes#create', as: "game_votes"


  # post 'users/:id/friendships' => 'friendships#create', as: "friendships"

  resources :tags


end

app/models/game.rb
class Game < ApplicationRecord
  after_save :create_tags

  belongs_to :user
  has_many :votes

  has_many :ownerships, foreign_key: :owned_game_id
  has_many :owners, through: :ownerships

  has_many :comments

  has_many :taggings
  has_many :tags, through: :taggings

  def vote_total
    self.votes.sum(:value)
  end

  private

  def create_tags
    unless self.initial_tags == nil
      game = Game.find(self.id)
      tags_array = self.initial_tags.split(" ")
      tags_array.each do |tag|
        tag = Tag.find_or_create_by(name: tag)
        game.tags << tag
      end
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :require_login, only: [:create]

  def index
    @vote = Vote.new
    @game = Game.new
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    user = User.find_by_id(session[:user_id])
    @ownership = Ownership.new
    @comment = @game.comments
    @tags = @game.tags
    # @ownership(owned_game: @game, owner: current_user)
  end

  def create
    user = User.find_by_id(session[:user_id])
    game = user.games.new(game_params)

    if game.save
      redirect_to '/'
    else
      redirect_to '/'
    end
  end

  def edit
    @game = Game.find(params[:id])
    if current_user && current_user.id == @game.user.id
    else
      redirect_to root_path
    end
  end

  def update
    @game = Game.find(params[:id])
    if @game.update_attributes(game_params)
      redirect_to @game
    else
      redirect_to :back
    end
  end

  private

  def game_params
    params.require(:game).permit(:title, :initial_tags, :description, :age_range, :num_players, :play_time, :image )
  end


  def require_login
    unless session[:user_id]
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_path
    end
  end


end

app/views/games/_form.html.erb
<div class="add-game">
	<%= form_for @game do |f| %>
	  <%= f.label :title, "Game Name" %>:
	  <%= f.text_field :title %>
    <%= f.label :initial_tags, "Tags" %>:
    <%= f.text_field :initial_tags, size: 25, placeholder: "separate tags by spaces" %><br><br>
    <%= f.label :description, "Description" %>:
    <%= f.text_area :description, cols: 50, rows: 4 %><br><br>
    <%= f.label :age_range, "Recommended Age" %>:
    <%= f.select :age_range, ['All Ages', 'Preschool', 'Children', 'Teen', 'Adult'] %>
    <%= f.label :num_players, "No.Players" %>:
    <%= f.select :num_players, ['1', '2', '2-4', '2-8'] %>
    <%= f.label :play_time, "Estimated Game Time" %>:
    <%= f.select :play_time, ['Up to 15 min', '15-30 min', '30-60 min', '60+ min'] %><br><br>

	  <%= f.submit "Add Game" %>
	<% end %>
</div>

app/views/games/_game.html.erb
<div class="single-game">

<%= render partial: 'games/votes', locals: {game: game} %>

<div class="game-box">
	<%= link_to game.title, game_path(game) %>
</div>

</div>
<!-- <p> Description: <%=game.description%> </p> -->

app/views/games/_ownership.html.erb
  <% if own_game? %>
    <%= form_for(:ownership, method: :delete, url: ownership_path(ownership)) do |f| %>
      <%= f.hidden_field :owner_id, :value => current_user.id %>
      <%= f.hidden_field :owned_game_id, :value => owned_game.id %>
      <%= f.submit "Remove from Collection" %>
    <% end %>
  <% else %>
  <%= form_for :ownership, url: ownerships_path do |f| %>
      <%= f.hidden_field :owner_id, :value => current_user.id %>
      <%= f.hidden_field :owned_game_id, :value => owned_game.id %>
      <%= f.submit "Add to Collection" %>
    <% end %>
  <% end %>

app/views/games/_votes.html.erb
<div class="votes-box" id="<%= "votesforgameID#{game.id}" %>">
  <%= form_for([game, game.votes.build], remote:true) do |f| %>
    <%= f.hidden_field :value, :value => 1 %>
    <%= image_submit_tag("uptriangle.png", class: "upvote-button "+up_button_class(game)) %>
  <% end %>
  <span class="vote-total">Votes: <%= game.vote_total %></span>
  <%= form_for([game, game.votes.build], remote:true) do |f| %>
    <%= f.hidden_field :value, :value => -1 %>
    <%= image_submit_tag("downtriangle.png", class: "downvote-button "+down_button_class(game))  %>
  <% end %>
</div>

app/views/games/edit.html.erb
<h2>Upload an image</h2>

<%= form_for :game, url: "/games/#{@game.id}", method: :patch do |f| %>

  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>

app/views/games/index.html.erb
<h1>Board to Death!</h1>


<div class="games-index">

  <h2> Add A Game: </h2>

  <%= render 'form' %>

  <h2> All Board Games </h2>

  <div id="game-list">
    <%= render @games.order('title ASC') %>
  </div>

</div>

app/views/games/show.html.erb
<div class="mid-content-box">
	<span class="inline-span">
		<h1> <%= @game.title %> </h1>
	</span>
	<span class="inline-span">
		<% if user_logged_in? %>
		  <%= render partial: "ownership", locals: {owned_game: @game, ownership: @game.ownerships.find_by(owner: current_user)} %>
		<% end %>
	</span>

	<div class="center-image">
		<%= image_tag @game.image, class: 'default_image' %>
	</div>
  <% if current_user && current_user.id == @game.user.id %>
    <%= link_to 'Edit Image', edit_game_path %>
  <% end %>


  <p> Description: <%= @game.description %> </p>
  <p> Recommended Age Range: <%= @game.age_range%> </p>
  <p> No. of Players: <%= @game.num_players %> </p>
  <p> Estimated Play Time: <%= @game.play_time %> </p><br>
  <p> Tags: <%= render @tags %></p>
</div>

<div class="mid-content-box">
	<h2>Comments: </h2>
		<%= render @comment %>

	<% if current_user %>
	  <%= link_to 'Add a Comment', new_comment_path %>
	<% end %>
</div>